# Generated by Django 4.2.4 on 2023-09-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.TextField(default='default title', verbose_name='тестируем умения'),
            preserve_default=False,
        ),
    ]
