# Generated by Django 4.2.4 on 2023-09-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_made',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_change',
            new_name='updated_at',
        ),
    ]
